In [2]:
import tensorflow as tf

In [4]:
# 2. Create a constant tensor
constant_tensor = tf.constant(10, dtype=tf.int32)
print("Constant Tensor:", constant_tensor)

# 3. Create a tensor filled with zeros
zeros_tensor = tf.zeros((2, 3), dtype=tf.float32)
print("\nZeros Tensor:", zeros_tensor)

# 4. Create a tensor filled with ones
ones_tensor = tf.ones((3, 2), dtype=tf.float32)
print("\nOnes Tensor:", ones_tensor)

# 5. Create a tensor with random values from a normal distribution
random_normal_tensor = tf.random.normal((2, 2), mean=0.0, stddev=1.0)
print("\nRandom Normal Tensor:", random_normal_tensor)

# 6. Create a tensor with random values from a uniform distribution
random_uniform_tensor = tf.random.uniform((3, 3), minval=0, maxval=10, dtype=tf.int32)
print("\nRandom Uniform Tensor:", random_uniform_tensor)

# 7. Create a tensor from a NumPy array
import numpy as np
numpy_array = np.array([[1, 2], [3, 4]])
tensor_from_numpy = tf.convert_to_tensor(numpy_array, dtype=tf.int64)
print("\nTensor from NumPy Array:", tensor_from_numpy)

Constant Tensor: tf.Tensor(10, shape=(), dtype=int32)

Zeros Tensor: tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)

Ones Tensor: tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)

Random Normal Tensor: tf.Tensor(
[[-0.71427286  0.07368384]
 [-0.2508329  -0.07013342]], shape=(2, 2), dtype=float32)

Random Uniform Tensor: tf.Tensor(
[[9 3 8]
 [2 5 5]
 [2 1 2]], shape=(3, 3), dtype=int32)

Tensor from NumPy Array: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int64)


In [5]:
# Create two tensors with compatible shapes
tensor_a = tf.constant([[1.0, 2.0], [3.0, 4.0]])
tensor_b = tf.constant([[5.0, 6.0], [7.0, 8.0]])

# Perform addition
addition_result = tensor_a + tensor_b
print("Addition Result:\n", addition_result)

# Perform subtraction
subtraction_result = tensor_a - tensor_b
print("\nSubtraction Result:\n", subtraction_result)

# Perform element-wise multiplication
multiplication_result = tensor_a * tensor_b
print("\nMultiplication Result:\n", multiplication_result)

# Perform element-wise division
division_result = tensor_a / tensor_b
print("\nDivision Result:\n", division_result)

Addition Result:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)

Subtraction Result:
 tf.Tensor(
[[-4. -4.]
 [-4. -4.]], shape=(2, 2), dtype=float32)

Multiplication Result:
 tf.Tensor(
[[ 5. 12.]
 [21. 32.]], shape=(2, 2), dtype=float32)

Division Result:
 tf.Tensor(
[[0.2        0.33333334]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float32)


In [6]:
# Create two tensors suitable for matrix multiplication
tensor_matmul_a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
tensor_matmul_b = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Perform matrix multiplication
matmul_result = tf.matmul(tensor_matmul_a, tensor_matmul_b)
print("Matrix Multiplication Result:\n", matmul_result)

# Create a tensor for transpose
tensor_transpose = tf.constant([[1, 2, 3], [4, 5, 6]])

# Perform transpose operation
transposed_tensor = tf.transpose(tensor_transpose)
print("\nOriginal Tensor for Transpose:\n", tensor_transpose)
print("Transposed Tensor:\n", transposed_tensor)

# Create a tensor for reshape
tensor_reshape = tf.constant([1, 2, 3, 4, 5, 6])

# Reshape the tensor
reshaped_tensor = tf.reshape(tensor_reshape, (2, 3))
print("\nOriginal Tensor for Reshape:\n", tensor_reshape)
print("Reshaped Tensor:\n", reshaped_tensor)

Matrix Multiplication Result:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)

Original Tensor for Transpose:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
Transposed Tensor:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

Original Tensor for Reshape:
 tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
Reshaped Tensor:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
# 1. Create several TensorFlow tensors with different shapes and data types
tensor1 = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.float32)
tensor2 = tf.constant([1.0, 2.0, 3.0, 4.0])
tensor3 = tf.constant([[1, 2], [3, 4], [5, 6]], dtype=tf.int32)
tensor4 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=tf.float32)
print("tensor1:\n", tensor1)
print("\ntensor2:\n", tensor2)
print("\ntensor3:\n", tensor3)
print("\ntensor4:\n", tensor4)

tensor1:
 tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)

tensor2:
 tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)

tensor3:
 tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

tensor4:
 tf.Tensor(
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]], shape=(2, 2, 2), dtype=float32)


In [8]:
# 2. Demonstrate the use of TensorFlow functions for mathematical operations
print("\nMathematical Operations:")
print("tf.reduce_sum(tensor1):", tf.reduce_sum(tensor1))
print("tf.reduce_mean(tensor1):", tf.reduce_mean(tensor1))
print("tf.maximum(tensor1, 3):", tf.maximum(tensor1, 3.0)) # Note the dtype matching
print("tf.minimum(tensor1, 3):", tf.minimum(tensor1, 3.0)) # Note the dtype matching
print("tf.reduce_sum(tensor4, axis=[1, 2]):", tf.reduce_sum(tensor4, axis=[1, 2]))


Mathematical Operations:
tf.reduce_sum(tensor1): tf.Tensor(21.0, shape=(), dtype=float32)
tf.reduce_mean(tensor1): tf.Tensor(3.5, shape=(), dtype=float32)
tf.maximum(tensor1, 3): tf.Tensor(
[[3. 3. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
tf.minimum(tensor1, 3): tf.Tensor(
[[1. 2. 3.]
 [3. 3. 3.]], shape=(2, 3), dtype=float32)
tf.reduce_sum(tensor4, axis=[1, 2]): tf.Tensor([10. 26.], shape=(2,), dtype=float32)


In [9]:
# 3. Demonstrate the use of TensorFlow functions for shape manipulation
print("\nShape Manipulation:")
tensor_with_single_dim = tf.constant([[1.0], [2.0], [3.0]])
squeezed_tensor = tf.squeeze(tensor_with_single_dim)
print("Original tensor with single dimension:\n", tensor_with_single_dim)
print("tf.squeeze(tensor_with_single_dim):\n", squeezed_tensor)

expanded_tensor = tf.expand_dims(squeezed_tensor, axis=0)
print("tf.expand_dims(squeezed_tensor, axis=0):\n", expanded_tensor)


Shape Manipulation:
Original tensor with single dimension:
 tf.Tensor(
[[1.]
 [2.]
 [3.]], shape=(3, 1), dtype=float32)
tf.squeeze(tensor_with_single_dim):
 tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.expand_dims(squeezed_tensor, axis=0):
 tf.Tensor([[1. 2. 3.]], shape=(1, 3), dtype=float32)


In [10]:
# 4. Demonstrate the use of TensorFlow functions for slicing and joining tensors
print("\nSlicing and Joining:")
sliced_tensor = tf.slice(tensor1, begin=[0, 1], size=[1, 2])
print("tf.slice(tensor1, begin=[0, 1], size=[1, 2]):\n", sliced_tensor)

tensor_concat1 = tf.constant([[10, 20]], dtype=tf.float32)
tensor_concat2 = tf.constant([[30, 40]], dtype=tf.float32)
concatenated_tensor = tf.concat([tensor_concat1, tensor_concat2], axis=1)
print("tf.concat([tensor_concat1, tensor_concat2], axis=1):\n", concatenated_tensor)

concatenated_tensor_axis0 = tf.concat([tensor_concat1, tensor_concat2], axis=0)
print("tf.concat([tensor_concat1, tensor_concat2], axis=0):\n", concatenated_tensor_axis0)


Slicing and Joining:
tf.slice(tensor1, begin=[0, 1], size=[1, 2]):
 tf.Tensor([[2. 3.]], shape=(1, 2), dtype=float32)
tf.concat([tensor_concat1, tensor_concat2], axis=1):
 tf.Tensor([[10. 20. 30. 40.]], shape=(1, 4), dtype=float32)
tf.concat([tensor_concat1, tensor_concat2], axis=0):
 tf.Tensor(
[[10. 20.]
 [30. 40.]], shape=(2, 2), dtype=float32)


## Summary:

### Data Analysis Key Findings

*   Various TensorFlow 2 tensors were successfully created, including constant tensors, tensors of zeros and ones, random tensors from normal and uniform distributions, and tensors converted from NumPy arrays.
*   Basic arithmetic operations (addition, subtraction, element-wise multiplication, and element-wise division) were performed on compatible tensors using standard Python operators.
*   Advanced tensor operations such as matrix multiplication (`tf.matmul`), transpose (`tf.transpose`), and reshaping (`tf.reshape`) were successfully demonstrated.
*   Several TensorFlow functions for tensor manipulation were illustrated, including mathematical operations (`tf.reduce_sum`, `tf.reduce_mean`, `tf.maximum`, `tf.minimum`), shape manipulation (`tf.squeeze`, `tf.expand_dims`), and slicing and joining (`tf.slice`, `tf.concat`).

