Name: Shivprasad A. Mahind;
PRN: 123B1B266

In [ ]:
#Tensorflow 2 basics & Tensor Operations

import tensorflow as tf
print("\n--- Tensorflow Version ---")
print(tf.__version__)


--- Tensorflow Version ---
2.18.0


In [ ]:
#---------------------------
#1. Tensor Creation Basics
#---------------------------

print("/n--- Tensor Creation ---")

#scaler (0D Tensor)
tensor_0d = tf.constant(9)
print("Scaler (OD): ", tensor_0d)
print()

#vector (1D Tensor)
tensor_1d = tf.constant([4, 5, 6])
print("Vector (1D): ", tensor_1d)
print()

#Matrix (2D Tensor)
tensor_2d = tf.constant([[2, 3], [6, 8]])
print("Matrix (2D): ", tensor_2d)
print()

# 3D Tensor (e.g., a batch of 2 images with 2x2 pixels and 1 channel)
tensor_3d = tf.constant([[[5], [3]], [[9], [7]]])
print("3D Tensor:\n", tensor_3d)
print()

/n--- Tensor Creation ---
Scaler (OD):  tf.Tensor(9, shape=(), dtype=int32)

Vector (1D):  tf.Tensor([4 5 6], shape=(3,), dtype=int32)

Matrix (2D):  tf.Tensor(
[[2 3]
 [6 8]], shape=(2, 2), dtype=int32)

3D Tensor:
 tf.Tensor(
[[[5]
  [3]]

 [[9]
  [7]]], shape=(2, 2, 1), dtype=int32)



In [ ]:
#----------------------
# 2. Tensor Properties
#----------------------

print("\n--- Tensor Properties ---")
print("Shape:", tensor_2d.shape)
print("Rank:", tf.rank(tensor_2d))
print("Datatype:", tensor_2d.dtype)


--- Tensor Properties ---
Shape: (2, 2)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Datatype: <dtype: 'int32'>


In [ ]:
#-------------------------------------
# 3. Creating Tensors Using Functions
#-------------------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Creating Special Tensors ---")
zeros_tensor = tf.zeros([2, 3])
ones_tensor = tf.ones([2, 3])
random_tensor = tf.random.uniform([2, 2], minval = 0, maxval = 10)

print_tensor("Zeros Tensor", zeros_tensor)
print_tensor("Ones Tensor", ones_tensor)
print_tensor("Random Tensor", random_tensor)


--- Creating Special Tensors ---
Zeros Tensor:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Tensor:
[[1. 1. 1.]
 [1. 1. 1.]]

Random Tensor:
[[2.0980752 5.642445 ]
 [9.746769  3.2489705]]



In [ ]:
# --------------------------
# 4. Basic Arithmetic Operations
# --------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Basic Arithmetic Operations ---")
a = tf.constant([[25, 73], [51, 37]])
b = tf.constant([[2, 7], [3, 5]])

print_tensor("a + b = \n", tf.add(a, b))
print_tensor("a - b = \n", tf.subtract(a, b))
print_tensor("a * b (element-wise) = \n", tf.multiply(a, b))
print_tensor("a / b = \n", tf.divide(a, b))


--- Basic Arithmetic Operations ---
a + b = 
:
[[27 80]
 [54 42]]

a - b = 
:
[[23 66]
 [48 32]]

a * b (element-wise) = 
:
[[ 50 511]
 [153 185]]

a / b = 
:
[[12.5        10.42857143]
 [17.          7.4       ]]



In [ ]:
# --------------------------
# 5. Matrix Multiplication
# --------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Matrix Multiplication ---")
print_tensor("a @ b = \n", tf.matmul(a, b))


--- Matrix Multiplication ---
a @ b = 
:
[[269 540]
 [213 542]]



In [ ]:
# --------------------------
# 6. Reshaping and Transposing
# --------------------------

print("\n--- Reshaping and Transposing ---")
tensor = tf.constant([[2, 5, 7], [6, 3, 8]])  # shape (2, 3)
reshaped = tf.reshape(tensor, [2, 3])        # shape (3, 2)
transposed = tf.transpose(tensor)            # shape (3, 2)

print("Original Tensor:\n", tensor.numpy())
print("Reshaped Tensor (3,2):\n", reshaped.numpy())
print("Transposed Tensor:\n", transposed.numpy())


--- Reshaping and Transposing ---
Original Tensor:
 [[2 5 7]
 [6 3 8]]
Reshaped Tensor (3,2):
 [[2 5 7]
 [6 3 8]]
Transposed Tensor:
 [[2 6]
 [5 3]
 [7 8]]


In [ ]:
# --------------------------
# 7. Type Casting
# --------------------------

print("\n--- Type Casting ---")
int_tensor = tf.constant([5, 2, 9])
float_tensor = tf.cast(int_tensor, dtype=tf.float32)

print("Original (int): ", int_tensor)
print("Casted (float): ", float_tensor)

print("Original (int): ", int_tensor.numpy())
print("Casted (float): ", float_tensor.numpy())


--- Type Casting ---
Original (int):  tf.Tensor([5 2 9], shape=(3,), dtype=int32)
Casted (float):  tf.Tensor([5. 2. 9.], shape=(3,), dtype=float32)
Original (int):  [5 2 9]
Casted (float):  [5. 2. 9.]


In [ ]:
# --------------------------
# 8. Indexing and Slicing
# --------------------------

print("\n--- Indexing and Sclicing ---")
data = tf.constant([[32, 24, 63], [13, 73, 85]])
print("Second row: ", data[1])
print("Element at [0, 2]: ", data[0, 2])
print("First column: ", data[:, 0])


--- Indexing and Sclicing ---
Second row:  tf.Tensor([13 73 85], shape=(3,), dtype=int32)
Element at [0, 2]:  tf.Tensor(63, shape=(), dtype=int32)
First column:  tf.Tensor([32 13], shape=(2,), dtype=int32)


In [ ]:
# --------------------------
# 9. Broadcasting
# --------------------------

print("\n--- Broadcasting Example ---")
x = tf.constant([[1], [2], [3]])
y = tf.constant([[32, 63, 87]])

broadcast_sum = x + y
print("Broadcast Sum:\n", broadcast_sum.numpy())


--- Broadcasting Example ---
Broadcast Sum:
 [[33 64 88]
 [34 65 89]
 [35 66 90]]


In [ ]:
# --------------------------
# 10. Logical Operations
# --------------------------

print("\n--- Logical Operations ---")
tensor_a = tf.constant([4, 2, 5, 1, 7])
tensor_b = tf.constant([2, 5, 1, 9, 7])

print("Equal: ", tf.equal(tensor_a, tensor_b))
print("Greater: ", tf.greater(tensor_a, tensor_b))


--- Logical Operations ---
Equal:  tf.Tensor([False False False False  True], shape=(5,), dtype=bool)
Greater:  tf.Tensor([ True False  True False False], shape=(5,), dtype=bool)


In [1]:
#Tensorflow 2 basics & Tensor Operations

import tensorflow as tf
print("\n--- Tensorflow Version ---")
print(tf.__version__)

#---------------------------
#1. Tensor Creation Basics
#---------------------------

print("/n--- Tensor Creation ---")

#scaler (0D Tensor)
tensor_0d = tf.constant(9)
print("Scaler (OD): ", tensor_0d)
print()

#vector (1D Tensor)
tensor_1d = tf.constant([4, 5, 6])
print("Vector (1D): ", tensor_1d)
print()

#Matrix (2D Tensor)
tensor_2d = tf.constant([[2, 3], [6, 8]])
print("Matrix (2D): ", tensor_2d)
print()

# 3D Tensor (e.g., a batch of 2 images with 2x2 pixels and 1 channel)
tensor_3d = tf.constant([[[5], [3]], [[9], [7]]])
print("3D Tensor:\n", tensor_3d)
print()

#----------------------
# 2. Tensor Properties
#----------------------

print("\n--- Tensor Properties ---")
print("Shape:", tensor_2d.shape)
print("Rank:", tf.rank(tensor_2d))
print("Datatype:", tensor_2d.dtype)

#-------------------------------------
# 3. Creating Tensors Using Functions
#-------------------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Creating Special Tensors ---")
zeros_tensor = tf.zeros([2, 3])
ones_tensor = tf.ones([2, 3])
random_tensor = tf.random.uniform([2, 2], minval = 0, maxval = 10)

print_tensor("Zeros Tensor", zeros_tensor)
print_tensor("Ones Tensor", ones_tensor)
print_tensor("Random Tensor", random_tensor)

# --------------------------
# 4. Basic Arithmetic Operations
# --------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Basic Arithmetic Operations ---")
a = tf.constant([[25, 73], [51, 37]])
b = tf.constant([[2, 7], [3, 5]])

print_tensor("a + b = \n", tf.add(a, b))
print_tensor("a - b = \n", tf.subtract(a, b))
print_tensor("a * b (element-wise) = \n", tf.multiply(a, b))
print_tensor("a / b = \n", tf.divide(a, b))

# --------------------------
# 5. Matrix Multiplication
# --------------------------

def print_tensor(title, tensor):
  print(f"{title}:\n{tensor}\n")

print("\n--- Matrix Multiplication ---")
print_tensor("a @ b = \n", tf.matmul(a, b))

# --------------------------
# 6. Reshaping and Transposing
# --------------------------

print("\n--- Reshaping and Transposing ---")
tensor = tf.constant([[2, 5, 7], [6, 3, 8]])  # shape (2, 3)
reshaped = tf.reshape(tensor, [2, 3])        # shape (3, 2)
transposed = tf.transpose(tensor)            # shape (3, 2)

print("Original Tensor:\n", tensor.numpy())
print("Reshaped Tensor (3,2):\n", reshaped.numpy())
print("Transposed Tensor:\n", transposed.numpy())

# --------------------------
# 7. Type Casting
# --------------------------

print("\n--- Type Casting ---")
int_tensor = tf.constant([5, 2, 9])
float_tensor = tf.cast(int_tensor, dtype=tf.float32)

print("Original (int): ", int_tensor)
print("Casted (float): ", float_tensor)

print("Original (int): ", int_tensor.numpy())
print("Casted (float): ", float_tensor.numpy())

# --------------------------
# 8. Indexing and Slicing
# --------------------------

print("\n--- Indexing and Sclicing ---")
data = tf.constant([[32, 24, 63], [13, 73, 85]])
print("Second row: ", data[1])
print("Element at [0, 2]: ", data[0, 2])
print("First column: ", data[:, 0])

# --------------------------
# 9. Broadcasting
# --------------------------

print("\n--- Broadcasting Example ---")
x = tf.constant([[1], [2], [3]])
y = tf.constant([[32, 63, 87]])

broadcast_sum = x + y
print("Broadcast Sum:\n", broadcast_sum.numpy())

# --------------------------
# 10. Logical Operations
# --------------------------

print("\n--- Logical Operations ---")
tensor_a = tf.constant([4, 2, 5, 1, 7])
tensor_b = tf.constant([2, 5, 1, 9, 7])

print("Equal: ", tf.equal(tensor_a, tensor_b))
print("Greater: ", tf.greater(tensor_a, tensor_b))


--- Tensorflow Version ---
2.19.0
/n--- Tensor Creation ---
Scaler (OD):  tf.Tensor(9, shape=(), dtype=int32)

Vector (1D):  tf.Tensor([4 5 6], shape=(3,), dtype=int32)

Matrix (2D):  tf.Tensor(
[[2 3]
 [6 8]], shape=(2, 2), dtype=int32)

3D Tensor:
 tf.Tensor(
[[[5]
  [3]]

 [[9]
  [7]]], shape=(2, 2, 1), dtype=int32)


--- Tensor Properties ---
Shape: (2, 2)
Rank: tf.Tensor(2, shape=(), dtype=int32)
Datatype: <dtype: 'int32'>

--- Creating Special Tensors ---
Zeros Tensor:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Tensor:
[[1. 1. 1.]
 [1. 1. 1.]]

Random Tensor:
[[1.218164  0.5167198]
 [3.0376995 9.162111 ]]


--- Basic Arithmetic Operations ---
a + b = 
:
[[27 80]
 [54 42]]

a - b = 
:
[[23 66]
 [48 32]]

a * b (element-wise) = 
:
[[ 50 511]
 [153 185]]

a / b = 
:
[[12.5        10.42857143]
 [17.          7.4       ]]


--- Matrix Multiplication ---
a @ b = 
:
[[269 540]
 [213 542]]


--- Reshaping and Transposing ---
Original Tensor:
 [[2 5 7]
 [6 3 8]]
Reshaped Tensor (3,2):
 [[2 5 7]
 [6 